2023-08-01 10:41:35,099 | main_logger | MainProcess  |        <module>               | INFO  | Master execution started
2023-08-01 10:41:35,099 | main_logger | MainProcess  |        execute_pipeline_download | INFO  | calling the create_folder_structure function
2023-08-01 10:41:35,100 | main_logger | MainProcess  |        execute_pipeline_download | ERROR | error in execute_pipeline_download 'gh_pipeline_path'.
Traceback (most recent call last):
  File "/home/nandishms/test/download.py", line 172, in execute_pipeline_download
    download_file_from_github(repo_name, git_branch, file_path= f'{config_path["programs"]}{prj_nm}{config_path["gh_pipeline_path"]}{pipeline_name}{JSON}',
KeyError: 'gh_pipeline_path'
2023-08-01 10:41:35,100 | main_logger | MainProcess  |        <module>               | ERROR | exception occured 'gh_pipeline_path'
