2023-07-31 15:08:18,527 | main_logger | MainProcess  |        <module>               | INFO  | Master execution started
2023-07-31 15:08:18,527 | main_logger | MainProcess  |        execute_pipeline_download | INFO  | calling the create_folder_structure function
2023-07-31 15:08:18,527 | main_logger | MainProcess  |        execute_pipeline_download | INFO  | calling the common_files_downloads function
2023-07-31 15:08:19,484 | main_logger | MainProcess  |        execute_pipeline_download | INFO  | calling the orchestrate_calling function
2023-07-31 15:08:19,487 | main_logger | MainProcess  |        task_orc_execution     | INFO  | execution at task level
2023-07-31 15:08:22,131 | main_logger | MainProcess  |        send_mail              | INFO  | mail sent
2023-07-31 15:08:23,336 | main_logger | MainProcess  |        task_orc_execution     | ERROR | error in orchestrate_task_calling local variable 'source_conn_file_name' referenced before assignment.
Traceback (most recent call last):
  File "/home/nandishms/test/src/scripts/orchestration/orchestrate.py", line 608, in task_orc_execution
    execute_job(prj_nm,paths_data,task_nm,run_id,file_path,iter_value)
  File "/home/nandishms/test/src/scripts/orchestration/orchestrate.py", line 38, in execute_job
    raise error
  File "/home/nandishms/test/src/scripts/orchestration/orchestrate.py", line 35, in execute_job
    download.execute_engine(prj_nm,task_id,paths_data,run_id,file_path,iter_value)
  File "/home/nandishms/test/download.py", line 238, in execute_engine
    raise error
  File "/home/nandishms/test/download.py", line 228, in execute_engine
    download_task_files(prj_nm,task_name, config_path, repo_name,GIT_BRANCH)
  File "/home/nandishms/test/download.py", line 193, in download_task_files
    raise error
  File "/home/nandishms/test/download.py", line 162, in download_task_files
    nan = f'{config_path["gh_connections_json_path"]}{source_conn_file_name}{JSON}'
UnboundLocalError: local variable 'source_conn_file_name' referenced before assignment
2023-07-31 15:08:23,338 | main_logger | MainProcess  |        get_ind_task_status    | INFO  | rest_api_test task is Start
2023-07-31 15:08:23,339 | main_logger | MainProcess  |        task_orc_execution     | INFO  | Task rest_api_test Execution failed.
2023-07-31 15:08:26,160 | main_logger | MainProcess  |        send_mail              | INFO  | mail sent
